backend:
  name: git-gateway
  branch: master

# For lokal utvikling, bytt til:
# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1

locale: nb_NO

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: portfolio
    label: "Portfolio"
    label_singular: "Portfolioinnlegg"
    folder: src/content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Beskriving", name: "description", widget: "string" }
      - { label: "Dato", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true }
      - { label: "Bilde", name: "image", widget: "image", required: false }
      - { label: "Oppdragsgivar", name: "client", widget: "string", required: false }
      - { label: "Lenke til original", name: "link", widget: "string", required: false }
      - { label: "Stikkord", name: "tags", widget: "list", required: false }
      - { label: "Innhald", name: "body", widget: "markdown" }

  - name: aktuelt
    label: "Aktuelt"
    label_singular: "Innlegg"
    folder: src/content/aktuelt
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Dato", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true }
      - { label: "Bilde", name: "image", widget: "image", required: false }
      - { label: "Stikkord", name: "tags", widget: "list", required: false }
      - { label: "Innhald", name: "body", widget: "markdown" }
